#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'sqlite'
cookbook 'mysql'
cookbook 'memcached'
cookbook 'postgresql'
cookbook 'nodejs'
cookbook 'database'
cookbook 'rvm',
  git: 'git://github.com/fnichol/chef-rvm.git'